### ISSUE TITLE
Torch hub savepath

### ISSUE THREAD

**Issue by photosartd** [RogerQi/maskclip_onnx#1]
https://github.com/RogerQi/maskclip_onnx/blob/fef7d709bba75fbcb421728ab7f2578bbe53f807/maskclip_onnx/clip.py#L95

Hey, I stumbled upon a problem that feature splatting repository crashes when tries to load the CLIP model to TORCH_HUB_ROOT using your repo. It seems this line should look like:

```python
TORCH_HUB_ROOT = os.getenv("TORCH_HUB_ROOT", os.path.expandvars("$HOME/.torch_hub"))
```
So without a $ at the env var, otherwise it references the wrong path

**Comment by RogerQi** [comment]
Ah you are right, thanks for the pointer!
